
# KPI Businness


library(dplyr)
library(readr)

kpi      <- readRDS("data/processed/kpi.rds")
enriched <- readRDS("data/processed/enriched.rds")

# Complementary KPI
repeat_rate <- enriched %>%
  filter(!is.na(customer_id)) %>%
  group_by(customer_id) %>%
  summarise(orders = n_distinct(invoice_no)) %>%
  summarise(taux_reachat = mean(orders > 1)) %>%
  pull(taux_reachat)

kpi_table <- tibble(
  KPI = c("Total revenue (£)",
          "Number of orders",
          "Number of clients",
          "Average cart (£)",
          "Percentage of revenue generated by promotions",
          "Customer repurchase rate"),
  Valeur = c(
    format(round(kpi$total_revenue), big.mark = " "),
    format(kpi$total_orders, big.mark = " "),
    format(kpi$total_customers, big.mark = " "),
    round(kpi$avg_order_value, 2),
    paste0(round(kpi$promo_revenue_share * 100, 1), " %"),
    paste0(round(repeat_rate * 100, 1), " %")
  )
)

print(kpi_table)
write_csv2(kpi_table, "outputs/tables/kpi_summary.csv")
message("KPI Eexported")
